#
# Copyright (c) 2008-2010 Cisco Systems, Inc. All rights reserved.
#
# Cisco Systems, Inc. retains all right, title and interest (including all
# intellectual property rights) in and to this computer program, which is
# protected by applicable intellectual property laws.  Unless you have obtained
# a separate written license from Cisco Systems, Inc., you are not authorized
# to utilize all or a part of this computer program for any purpose (including
# reproduction, distribution, modification, and compilation into object code),
# and you must immediately destroy or return to Cisco Systems, Inc. all copies
# of this computer program.  If you are licensed by Cisco Systems, Inc., your
# rights to utilize this computer program are limited by the terms of that
# license.  To obtain a license, please contact Cisco Systems, Inc.
#
# This computer program contains trade secrets owned by Cisco Systems, Inc.
# and, unless unauthorized by Cisco Systems, Inc. in writing, you agree to
# maintain the confidentiality of this computer program and related information
# and to not disclose this computer program and related information to any
# other person or entity.
#
# THIS COMPUTER PROGRAM IS PROVIDED AS IS WITHOUT ANY WARRANTIES, AND CISCO
# SYSTEMS, INC. EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING THE WARRANTIES OF MERCHANTIBILITY, FITNESS FOR A PARTICULAR
# PURPOSE, TITLE, AND NONINFRINGEMENT.
#

# Build directory
ifndef BUILDDIR
BUILDDIR = build
endif

# Build target (default)
.PHONY: build
build:
	make -C libhdkxml BUILDDIR=$(abspath $(BUILDDIR))/libhdkxml
	make -C libhdksrv BUILDDIR=$(abspath $(BUILDDIR))/libhdksrv
	make -C libhdkcli BUILDDIR=$(abspath $(BUILDDIR))/libhdkcli
	make -C libhnap12 BUILDDIR=$(abspath $(BUILDDIR))/libhnap12
	make -C unittest BUILDDIR=$(abspath $(BUILDDIR))/unittest
	make -C spec BUILDDIR=$(abspath $(BUILDDIR))/doc

# Sample build target
.PHONY: sample
sample: build
	make -C sample/cgi BUILDDIR=$(abspath $(BUILDDIR))/sample/cgi
	make -C sample/client BUILDDIR=$(abspath $(BUILDDIR))/sample/client
	make -C sample/dom BUILDDIR=$(abspath $(BUILDDIR))/sample/dom
	make -C sample/hnapd BUILDDIR=$(abspath $(BUILDDIR))/sample/hnapd
	make -C sample/module BUILDDIR=$(abspath $(BUILDDIR))/sample/module

# Clean the build directory
.PHONY: clean
clean:
	make -C libhdkxml clean BUILDDIR=$(abspath $(BUILDDIR))/libhdkxml
	make -C libhdkxml/unittest clean
	make -C libhdksrv clean BUILDDIR=$(abspath $(BUILDDIR))/libhdksrv
	make -C libhdksrv/unittest clean
	make -C libhdkcli clean BUILDDIR=$(abspath $(BUILDDIR))/libhdkcli
	make -C libhdkcli/unittest clean
	make -C libhnap12 clean BUILDDIR=$(abspath $(BUILDDIR))/libhnap12
	make -C libhnap12/unittest clean
	make -C unittest clean BUILDDIR=$(abspath $(BUILDDIR))/unittest
	make -C spec clean BUILDDIR=$(abspath $(BUILDDIR))/doc
	make -C sample/cgi clean BUILDDIR=$(abspath $(BUILDDIR))/sample/cgi
	make -C sample/client clean BUILDDIR=$(abspath $(BUILDDIR))/sample/client
	make -C sample/dom clean BUILDDIR=$(abspath $(BUILDDIR))/sample/dom
	make -C sample/hnapd clean BUILDDIR=$(abspath $(BUILDDIR))/sample/hnapd
	make -C sample/module clean BUILDDIR=$(abspath $(BUILDDIR))/sample/module
ifeq ($(abspath $(BUILDDIR)), $(abspath build))
	@if [ -d $(BUILDDIR) ]; then rm -r -f $(BUILDDIR); fi
endif

# Run unit tests
.PHONY: runtests
runtests:
	python bin/unittest/runtests.py
	@echo
	python libhdkxml/unittest/runtests.py
	@echo
	python libhdksrv/unittest/runtests.py
	@echo
	python libhdkcli/unittest/runtests.py
	@echo
	python hdkcli_cpp/unittest/runtests.py
	@echo
	make -C libhnap12/unittest --silent
	@echo
	make -C sample/module/unittest --silent
	@echo
	make -C spec check BUILDDIR=$(abspath $(BUILDDIR))/doc

# Clean, build and test
.PHONY: check
check: clean build sample runtests
