#
# Copyright (c) 2008-2010 Cisco Systems, Inc. All rights reserved.
#
# Cisco Systems, Inc. retains all right, title and interest (including all
# intellectual property rights) in and to this computer program, which is
# protected by applicable intellectual property laws.  Unless you have obtained
# a separate written license from Cisco Systems, Inc., you are not authorized
# to utilize all or a part of this computer program for any purpose (including
# reproduction, distribution, modification, and compilation into object code),
# and you must immediately destroy or return to Cisco Systems, Inc. all copies
# of this computer program.  If you are licensed by Cisco Systems, Inc., your
# rights to utilize this computer program are limited by the terms of that
# license.  To obtain a license, please contact Cisco Systems, Inc.
#
# This computer program contains trade secrets owned by Cisco Systems, Inc.
# and, unless unauthorized by Cisco Systems, Inc. in writing, you agree to
# maintain the confidentiality of this computer program and related information
# and to not disclose this computer program and related information to any
# other person or entity.
#
# THIS COMPUTER PROGRAM IS PROVIDED AS IS WITHOUT ANY WARRANTIES, AND CISCO
# SYSTEMS, INC. EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING THE WARRANTIES OF MERCHANTIBILITY, FITNESS FOR A PARTICULAR
# PURPOSE, TITLE, AND NONINFRINGEMENT.
#

# Location of the HDK
HDKDIR = ..

# Build directory
!ifndef BUILDDIR
BUILDDIR = ..\build\unittest
!endif

# HDK library directories
!ifndef BUILDDIR_LIBHDKXML
BUILDDIR_LIBHDKXML = ..\build\libhdkxml
!endif
!ifndef BUILDDIR_LIBHDKSRV
BUILDDIR_LIBHDKSRV = ..\build\libhdksrv
!endif

# Targets
EXE = $(BUILDDIR)\unittest.exe

# Object files
OBJS = \
	"$(BUILDDIR)\unittest.obj"

# Compiler flags
!ifdef UNITTEST_CXX
UNITTEST_CC = $(CXX) /TP
UNITTEST_CFLAGS = $(CXXFLAGS)
!else
UNITTEST_CC = $(CC) /TC
UNITTEST_CFLAGS = $(CFLAGS)
!endif

# Enable highest warning level; treat warnings as errors
UNITTEST_CFLAGS = $(UNITTEST_CFLAGS) /W4 /WX /analyze
# Disable "'function': was declared deprecated" warning
UNITTEST_CFLAGS = $(UNITTEST_CFLAGS) /wd4996
UNITTEST_CFLAGS = $(UNITTEST_CFLAGS) /I$(HDKDIR)\include

!ifdef DEBUG
UNITTEST_CFLAGS = $(UNITTEST_CFLAGS) /Od /Zi /MDd
!else
UNITTEST_CFLAGS = $(UNITTEST_CFLAGS) /Os /MD
!endif

# Linker flags
LDFLAGS = /NOLOGO
LDFLAGS = $(LDFLAGS) "$(BUILDDIR_LIBHDKXML)\libhdkxml.lib" "$(BUILDDIR_LIBHDKSRV)\libhdksrv.lib"
!ifdef DEBUG
LDFLAGS = /DEBUG $(LDFLAGS)
!endif

# Build target (default)
build: $(EXE)

build_malloc_interposer:
	@echo Malloc_interposer not supported on Windows platforms

# Clean the build directory
clean:
	if exist "$(BUILDDIR)" @rmdir /s /q "$(BUILDDIR)"

# Rule for linking the executable
$(EXE): $(OBJS)
	link.exe $(LDFLAGS) $(**R) /OUT:$(EXE)

# Rules for compiling source files
{}.c{$(BUILDDIR)}.obj:
	@if not exist "$(BUILDDIR)" @mkdir "$(BUILDDIR)"
	$(UNITTEST_CC) $(UNITTEST_CFLAGS) /Fd$(*R) /Fo$@ /c $(<)
