#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#Makefile for utopia service wan code
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

CFLAGS += $(addprefix -I,$(INCPATH))
CFLAGS += -I../sysevent/lib
CFLAGS += -I../syscfg/lib
CFLAGS += -I../ulog
CFLAGS += -I../util
CFLAGS += -I./

LDFLAGS += -lsyscfg
LDFLAGS += -lsysevent
LDFLAGS += -lulog

targets_service_wan := service_wan
targets_service_wan := $(addprefix $(ComponentBuildDir)/,$(targets_service_wan))

source_files_service_wan := service_wan.c ../util/util.c
obj_files_service_wan := $(addprefix $(ComponentBuildDir)/,$(source_files_service_wan:%.c=%.o))

$(targets_service_wan): $(obj_files_service_wan)


all: $(targets_service_wan) install

clean: 
	rm -f $(ComponentBuildDir)

install:
	@echo "Copying...[$(targets_service_wan) to SBIN directory]"
	@install -d -m 0755 $(CCSP_INSTALL_ROOT)/sbin
	@install -m 0755 $(targets_service_wan) $(CCSP_INSTALL_ROOT)/sbin/

.PHONY : all clean install

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif
