#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#Makefile for utopia compiled registration code
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

install_script := $(call add_files_from_board,,utopia_init.sh)
install_script += $(call add_files_from_board,,need_wifi_default.sh)

target_install_dir := $(CCSP_INSTALL_ROOT)/etc/utopia

all: install

clean: 
	rm -f $(ComponentBuildDir)

install:
	@install -d -m 0755 $(target_install_dir)
	@echo "Copying...[$(install_script) to $(target_install_dir) directory]"
	@install -m 0755 $(install_script) $(target_install_dir)/

.PHONY: all clean install

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif

