/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_specification.h"
#include "errno.h"

struct rpc_CommandBuf output;
#define TEMP_BUF_LEN 255
extern FILE *logfp;


rpc_CommandBuf *
executecommand_1_svc(rpc_CommandBuf *argp, struct svc_req *rqstp)
{
	//argp->buffer size is 4096
	char cmdBuf[4110]={0};
  	int counter=0;
	snprintf(cmdBuf,sizeof(cmdBuf),"%s 2>&1",argp->buffer);
	RPC_PRINT("Server received command %s \n",cmdBuf);
	FILE *cmd = popen(cmdBuf, "r");
	if (! cmd)
	{
		RPC_PRINT("command failed %s , error (errno %d) %s \n",cmdBuf, errno, strerror(errno));
		return NULL;
	}
	char line [128] = {0}; /* or other suitable maximum line size */
	memset (output.buffer,0,4096);
        int MAXCOUNTER= (sizeof(output.buffer)/sizeof(line) );
		while ( fgets ( line, sizeof (line), cmd ) != NULL ) 
		{  
		   if (counter >= MAXCOUNTER ) 
                   {
                      if ( (strlen(output.buffer) + strlen(line) ) > sizeof(output.buffer) ) 
                              break;
                   }
			/*Here destination output.buffer size is 4096.
			As per safec limitation, it won't copy to the destination buffer , if destination size is more than 4K*/
			strcat(output.buffer,line);
                  	counter++;
		}
		pclose ( cmd );
		return &output;
}


int * exec_1_svc(rpc_CommandBuf *cmd, struct svc_req *req)
{
	//cmd->buffer size is 4096
	char cmdBuf[4100]={0};
	int ret = 1;
	snprintf(cmdBuf,sizeof(cmdBuf),"%s &",cmd->buffer);
	system(cmdBuf);
	return &ret;
}

