/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_specification.h"
#include "errno.h"

struct rpc_CommandBuf output;
#define TEMP_BUF_LEN 255
extern FILE *logfp;


rpc_CommandBuf *
executecommand_1_svc(rpc_CommandBuf *argp, struct svc_req *rqstp)
{
	char cmdBuf[255]={0};
  	int counter=0;
	snprintf(cmdBuf,TEMP_BUF_LEN,"%s 2>&1\n",argp->buffer);
	RPC_PRINT("Server received command %s \n",cmdBuf);
	FILE *cmd = popen(cmdBuf, "r");
	char line [128] = {0}; /* or other suitable maximum line size */
	memset (output.buffer,0,4096);
        int MAXCOUNTER= (sizeof(output.buffer)/sizeof(line) );
	if (cmd != NULL) {
		while ( fgets ( line, sizeof (line), cmd ) != NULL ) 
		{  
		   if (counter >= MAXCOUNTER ) 
                   {
                      if ( (strlen(output.buffer) + strlen(line) ) > sizeof(output.buffer) ) 
                              break;
                   }
			strcat(output.buffer,line);
			memset (line,0,128);
                  	counter++;
		}
		pclose ( cmd );
		return &output;
	}
	else
	{
	RPC_PRINT("command failed %s , error (errno %d) %s \n",cmdBuf, errno, strerror(errno)); 
	return 	NULL;
	}
}


int * exec_1_svc(rpc_CommandBuf *cmd, struct svc_req *req)
{
	char cmdBuf[255]={0};
	int ret = 1;
    snprintf(cmdBuf,TEMP_BUF_LEN,"%s &\n",cmd->buffer);
	system(cmdBuf);
	return &ret;
}

