/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SPECIFICATION_H_RPCGEN
#define _RPC_SPECIFICATION_H_RPCGEN

#include <rpc/rpc.h>

#define DEVICE_PROPERTIES "/etc/device.properties"

#ifdef _COSA_INTEL_USG_ARM_
        #define LOG_FILE "/rdklogs/logs/ArmConsolelog.txt.0"

#elif _COSA_INTEL_USG_ATOM_
        #define LOG_FILE "/rdklogs/logs/AtomConsolelog.txt.0"
#else
        #define LOG_FILE "/rdklogs/logs/rpcserver.txt"
#endif


#define RPC_PRINT(fmt ...)      logfp = fopen ( LOG_FILE , "a+");\
                                if (logfp)\
                                {\
                                        fprintf(logfp,fmt);\
                                        fclose(logfp);\
                                }\


#ifdef __cplusplus
extern "C" {
#endif


struct rpc_CommandBuf {
	char buffer[4096];
};
typedef struct rpc_CommandBuf rpc_CommandBuf;

#define RPC_TOOL1 0x2ff2322
#define RPC_TOOL1_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXECUTECOMMAND 1
extern  rpc_CommandBuf * executecommand_1(rpc_CommandBuf *, CLIENT *);
extern  rpc_CommandBuf * executecommand_1_svc(rpc_CommandBuf *, struct svc_req *);
#define exec 2
extern  int * exec_1(rpc_CommandBuf *, CLIENT *);
extern  int * exec_1_svc(rpc_CommandBuf *, struct svc_req *);
extern int rpc_tool1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXECUTECOMMAND 1
extern  rpc_CommandBuf * executecommand_1();
extern  rpc_CommandBuf * executecommand_1_svc();
#define exec 2
extern  int * exec_1();
extern  int * exec_1_svc();
extern int rpc_tool1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_CommandBuf (XDR *, rpc_CommandBuf*);

#else /* K&R C */
extern bool_t xdr_rpc_CommandBuf ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SPECIFICATION_H_RPCGEN */
