/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_specification.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_CommandBuf *
executecommand_1(rpc_CommandBuf *argp, CLIENT *clnt)
{
	static rpc_CommandBuf clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXECUTECOMMAND,
		(xdrproc_t) xdr_rpc_CommandBuf, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_CommandBuf, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
int *
exec_1(rpc_CommandBuf *argp, CLIENT *clnt)
{
        static int clnt_res;

        memset((char *)&clnt_res, 0, sizeof(clnt_res));
        if (clnt_call (clnt, exec,
                (xdrproc_t) xdr_rpc_CommandBuf, (caddr_t) argp,
                (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
                TIMEOUT) != RPC_SUCCESS) {
                return (NULL);
        }
        return (&clnt_res);
}

