#
# Copyright (c) 2008-2010 Cisco Systems, Inc. All rights reserved.
#
# Cisco Systems, Inc. retains all right, title and interest (including all
# intellectual property rights) in and to this computer program, which is
# protected by applicable intellectual property laws.  Unless you have obtained
# a separate written license from Cisco Systems, Inc., you are not authorized
# to utilize all or a part of this computer program for any purpose (including
# reproduction, distribution, modification, and compilation into object code),
# and you must immediately destroy or return to Cisco Systems, Inc. all copies
# of this computer program.  If you are licensed by Cisco Systems, Inc., your
# rights to utilize this computer program are limited by the terms of that
# license.  To obtain a license, please contact Cisco Systems, Inc.
#
# This computer program contains trade secrets owned by Cisco Systems, Inc.
# and, unless unauthorized by Cisco Systems, Inc. in writing, you agree to
# maintain the confidentiality of this computer program and related information
# and to not disclose this computer program and related information to any
# other person or entity.
#
# THIS COMPUTER PROGRAM IS PROVIDED AS IS WITHOUT ANY WARRANTIES, AND CISCO
# SYSTEMS, INC. EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING THE WARRANTIES OF MERCHANTIBILITY, FITNESS FOR A PARTICULAR
# PURPOSE, TITLE, AND NONINFRINGEMENT.
#

# Build target (default)
build: unittest

# Clean the build directory
clean:
	if exist build @rmdir /s /q build
	if exist actual @rmdir /s /q actual

# libhdkxml
libhdkxml:
	@pushd ..\..\libhdkxml & \
	nmake.exe /NOLOGO /f Makefile.nmake  BUILDDIR="..\hdkcli_cpp\unittest\build\libhdkxml" & \
	@popd

# libhdkcli
libhdkcli:
	@pushd ..\..\libhdkcli & \
	nmake.exe /NOLOGO /f Makefile.nmake BUILDDIR="..\hdkcli_cpp\unittest\build\libhdkcli" BUILDDIR_LIBHDKXML="..\hdkcli_cpp\unittest\build\libhdkxml" & \
	@popd

# unittest, libhdkxml, libhdkcli
unittest: libhdkxml libhdkcli
	@if not exist "build\unittest" @mkdir "build\unittest"
	copy "build\libhdkxml\libhdkxml.dll" "build\unittest"
	copy "build\libhdkxml\libhdkxml.lib" "build\unittest"
	copy "build\libhdkxml\libexpat.dll" "build\unittest"
	copy "build\libhdkcli\libhdkcli.dll" "build\unittest"
	copy "build\libhdkcli\libhdkcli.lib" "build\unittest"
	nmake.exe /NOLOGO /f Makefile.build.nmake BUILDDIR="build\unittest"
